
// This file has been generated by the GUI designer. Do not modify.
namespace BeaJay
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action OpenAction;
		
		private global::Gtk.Action AboutAction;
		
		private global::Gtk.Action ExitAction;
		
		private global::Gtk.VBox baseVerticalSplit;
		
		private global::Gtk.MenuBar menubar2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView debugSerialise;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BeaJay.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
			this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
			w1.Add (this.OpenAction, null);
			this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
			this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.AboutAction, null);
			this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.ExitAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "BeaJay.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Medico Main Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child BeaJay.MainWindow.Gtk.Container+ContainerChild
			this.baseVerticalSplit = new global::Gtk.VBox ();
			this.baseVerticalSplit.Name = "baseVerticalSplit";
			this.baseVerticalSplit.Spacing = 6;
			// Container child baseVerticalSplit.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='OpenAction' action='OpenAction'/><menuitem name='AboutAction' action='AboutAction'/><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.baseVerticalSplit.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.baseVerticalSplit [this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child baseVerticalSplit.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.debugSerialise = new global::Gtk.TextView ();
			this.debugSerialise.CanFocus = true;
			this.debugSerialise.Name = "debugSerialise";
			this.GtkScrolledWindow.Add (this.debugSerialise);
			this.baseVerticalSplit.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.baseVerticalSplit [this.GtkScrolledWindow]));
			w4.Position = 1;
			this.Add (this.baseVerticalSplit);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 465;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.OpenAction.Activated += new global::System.EventHandler (this.OnOpen);
			this.AboutAction.Activated += new global::System.EventHandler (this.OnAbout);
			this.ExitAction.Activated += new global::System.EventHandler (this.OnExit);
		}
	}
}
