.PHONY: clean All

All:
	@echo "----------Building project:[ Version0 - Debug ]----------"
	@cd "Version0" && $(MAKE) -f  "Version0.mk"
clean:
	@echo "----------Cleaning project:[ Version0 - Debug ]----------"
	@cd "Version0" && $(MAKE) -f  "Version0.mk" clean
